services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  db:
    build: docker/db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "4000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5555:80"
    depends_on:
      - db
    logging:
      driver: none

volumes:
  db-data:
    driver: local
