services:
  web:
    build: docker/web
    working_dir: /src/web
    # user: "1000"
    user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
    volumes:
      - ./web:/src/web
    ports:
      - "8080:8080"
    command: [ "npm", "run", "serve" ]


  api:
    build: docker/api
    volumes:
      - ./api:/var/task
    working_dir: /var/task
    ports:
      - "127.0.0.1:5000:5000"
    user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
    environment:
      - HOME=/tmp

    entrypoint: [ 'poetry', 'run' ]
    command: ["flask", "run", "--host=0.0.0.0"]
    env_file: ./docker/.env
    depends_on: [db]

  db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "4000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default


volumes:
  db-data:
    driver: local
